on:
  # for manual triggers
  workflow_dispatch:
  # for calling the workflow from another workflow
  workflow_call:

jobs:
  write_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find the number of the first open pr and merge it
        id: find_pr_number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --state open --limit 1 --json number --jq '.[0].number')
          gh pr merge $pr_number --merge
        shell: bash
